### ISSUE TITLE
Stylized's Semigroup is not lawful (Associative)

### ISSUE THREAD

**Issue by ramirez7** [pjones/byline#16]
I wrote up a quick test to show this law breaking:
```haskell
main :: IO ()
main = void $ runBylineT $ do
  sayLn ("Hey, I like " <> ("Haskell" <> fg magenta) <> "!")
  sayLn ("Hey, I like " <> "Haskell" <> fg magenta <> "!")
  sayLn ("Hey, I like " <> "Haskell" <> (fg magenta <> "!"))
```

For the latter two, the `!` is magenta. For the first one, `Haskell` is magenta. Since this difference is caused just by me rearranging parentheses, it means `<>` is not associative.

I tried replacing `fg magenta` with other modifiers (`bg magenta`, `bold`, etc) and the results are the same.

3 options off the top of my head:
1. Let the Semigroup be unlawful. I don't think this is a good route since Semigroup's laws are pretty much all it has - and people definitely intuitively use them to reason about code.
2. Change modifiers to be curried functions of `Stylized Text -> Stylized Text`. This is a pretty common type for APIs like this. Then the code would look like this (barely different):
```haskell
import Data.Function (&)
main :: IO ()
main = void $ runBylineT $ do
  sayLn ("Hey, I like " <> ("Haskell" & fg magenta) <> "!")
  sayLn ("Hey, I like " <> "Haskell" <> (fg magenta & "!"))
```
3. Drop the Semigroup entirely and just use a custom `<>`-like operator. Probably not a good idea since `Semigroup` opens up a lot of other niceties.

**Comment by pjones** [comment]
@ramirez7 Thank you for taking the time to report this and providing solutions.  I really like the second option where modifiers are curried functions.

Is there any chance you could start making some of those changes and open a PR?
