### ISSUE TITLE
Support Dull / Vivid ANSI ColorIntensity

### ISSUE THREAD

**Issue by benrbray** [pjones/byline#19]
The [`System.Console.ANSI` package](https://hackage.haskell.org/package/ansi-terminal-0.5.0/docs/System-Console-ANSI.html) has additional options for `ColorIntensity = Vivid | Dull`.  Would you accept a PR adding support for this style of formatting?

I took a quick look at the source, and it looks like it should be possible with the following steps:

* add a [new modifier](https://github.com/pjones/byline/blob/trunk/src/Byline/Internal/Types.hs#L75) called `modIntensity` 

https://github.com/pjones/byline/blob/2f1b84ea64d87656f372350e4c183d33afcd6a92/src/Byline/Internal/Types.hs#L75-L82

* update the [getColor](https://github.com/pjones/byline/blob/a5e3001333b0ca4e5ddad522d67fd6d372a5bcd7/src/Byline/Internal/Stylized.hs#L237) helper inside of [modToSGR](https://github.com/pjones/byline/blob/a5e3001333b0ca4e5ddad522d67fd6d372a5bcd7/src/Byline/Internal/Stylized.hs#L221), to work with the new modifier

https://github.com/pjones/byline/blob/a5e3001333b0ca4e5ddad522d67fd6d372a5bcd7/src/Byline/Internal/Stylized.hs#L228-L250

* allow the modifier to override the default value of `ANSI.Dull` set by [Simple](https://github.com/pjones/byline/blob/a5e3001333b0ca4e5ddad522d67fd6d372a5bcd7/src/Byline/Internal/Stylized.hs#L195) and [TermRGB](https://github.com/pjones/byline/blob/a5e3001333b0ca4e5ddad522d67fd6d372a5bcd7/src/Byline/Internal/Stylized.hs#L204) cases

https://github.com/pjones/byline/blob/a5e3001333b0ca4e5ddad522d67fd6d372a5bcd7/src/Byline/Internal/Stylized.hs#L187-L206

**Comment by pjones** [comment]
I think this would be a great change and welcome a PR.  Thanks!
