### ISSUE TITLE
GHC 9.2.5 support

### ISSUE THREAD

**Issue by Arraying** [pjones/byline#22]
I am trying to install Byline in a Stack project using GHC 9.2.5:
```
In the dependencies for byline-1.1.1:
    haskeline-0.8.2 from stack configuration does not match >=0.8 && <0.8.2  (latest matching version is 0.8.1.3)
    optparse-applicative-0.17.0.0 from stack configuration does not match ^>=0.16  (latest matching version is 0.16.1.0)
    relude-1.1.0.0 from stack configuration does not match >=0.6 && <1.1  (latest matching version is 1.0.0.1)
    terminfo-hs must match >=0.1 && <0.3, but the stack configuration has no specified version  (latest matching version is 0.2.1.1)
needed since byline is a build target.
```

Adding these to my `extra-deps` as per Stack's suggestion yields:
```
In the dependencies for relude-1.0.0.1:
    base-4.16.4.0 from stack configuration does not match >=4.10 && <4.16  (latest matching version is 4.15.1.0)
    ghc-prim-0.8.0 from stack configuration does not match >=0.4.0.0 && <0.8  (latest matching version is 0.7.0)
    hashable-1.4.2.0 from stack configuration does not match >=1.2 && <1.4  (latest matching version is 1.3.5.0)
needed due to byline-1.1.1 -> relude-1.0.0.1
```

I'm a newbie at Haskell, but it seems to me like Byline's dependency constraints could be updated.

**Comment by pjones** [comment]
You are correct, the constraints are most likely out of date given the version of Stack and GHC that you are using.

Unfortunately I don't currently have enough free time to address this.  That said, it's a simple fix and if you open a PR with the necessary changes I would approve it and push a new version to Hackage.

**Comment by Arraying** [comment]
I've opened a PR for this: #23

**Comment by pjones** [comment]
@Arraying: 1.1.2 was pushed to [Hackage](https://hackage.haskell.org/package/byline-1.1.2).

Thank you for your help!
