### ISSUE TITLE
Allow Byline to be used within other transformer stacks

### ISSUE THREAD

**Issue by samtay** [pjones/byline#3]
Is there a specific design reason for not implementing `MonadTrans` or exposing `liftBase`? My use case is, I think, a common one: use `byline` as an interface to read, modify, and interact with a much more complicated datatype within a `StateT` transformer.

Specifically, my app looks like `type App = ReaderT AppConfig (StateT AppState IO)`. At some point after gathering configuration and setting up initial state, I'd like to `runPrompt :: App ()` where
```haskell
runPrompt :: App ()
runPrompt = runByline $ do
  app_state <- get
  -- or
  app_state <- liftBase get
  sayLn $ "Here's something specific from my app state" <> render app_state
```

Am I missing something? Is there already a way to do this? Let me know what you think. Thanks!

**Comment by pjones** [comment]
Nope, there's no particular reason for this, just shortsightedness on my part.  Patches welcome ;)
